-- RAW tables preserve source values used by the analysis DWH.

CREATE TABLE IF NOT EXISTS RAW.STOCK_PRICES (
    STOCK_CODE VARCHAR NOT NULL,
    TRADE_DATE DATE NOT NULL,
    OPEN_PRICE FLOAT,
    HIGH_PRICE FLOAT,
    LOW_PRICE FLOAT,
    CLOSE_PRICE FLOAT,
    VOLUME NUMBER,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (STOCK_CODE, TRADE_DATE)
);

ALTER TABLE RAW.STOCK_PRICES
    ADD COLUMN IF NOT EXISTS LOADED_AT TIMESTAMP_NTZ;

CREATE TABLE IF NOT EXISTS RAW.FINANCE (
    STOCK_CODE VARCHAR NOT NULL,
    FISCAL_YEAR NUMBER NOT NULL,
    SALES FLOAT,
    OPERATING_PROFIT FLOAT,
    NET_PROFIT FLOAT,
    ROE FLOAT,
    PER FLOAT,
    PBR FLOAT,
    DIVIDEND_YIELD FLOAT,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (STOCK_CODE, FISCAL_YEAR)
);

CREATE TABLE IF NOT EXISTS RAW.MACRO_ECONOMIC (
    TRADE_DATE DATE NOT NULL,
    USD_JPY FLOAT,
    NIKKEI_CLOSE FLOAT,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (TRADE_DATE)
);
