-- CLEAN views normalize types and remove duplicate RAW rows without losing source data.

CREATE OR REPLACE VIEW CLEAN.STOCK_PRICES AS
SELECT
    STOCK_CODE::VARCHAR AS STOCK_CODE,
    TRADE_DATE::DATE AS TRADE_DATE,
    OPEN_PRICE::FLOAT AS OPEN_PRICE,
    HIGH_PRICE::FLOAT AS HIGH_PRICE,
    LOW_PRICE::FLOAT AS LOW_PRICE,
    CLOSE_PRICE::FLOAT AS CLOSE_PRICE,
    VOLUME::NUMBER AS VOLUME,
    LOADED_AT
FROM RAW.STOCK_PRICES
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY STOCK_CODE, TRADE_DATE
    ORDER BY LOADED_AT DESC
) = 1;

CREATE OR REPLACE VIEW CLEAN.FINANCE AS
SELECT
    STOCK_CODE::VARCHAR AS STOCK_CODE,
    FISCAL_YEAR::NUMBER AS FISCAL_YEAR,
    SALES::FLOAT AS SALES,
    OPERATING_PROFIT::FLOAT AS OPERATING_PROFIT,
    NET_PROFIT::FLOAT AS NET_PROFIT,
    ROE::FLOAT AS ROE,
    PER::FLOAT AS PER,
    PBR::FLOAT AS PBR,
    DIVIDEND_YIELD::FLOAT AS DIVIDEND_YIELD,
    LOADED_AT
FROM RAW.FINANCE
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY STOCK_CODE, FISCAL_YEAR
    ORDER BY LOADED_AT DESC
) = 1;

CREATE OR REPLACE VIEW CLEAN.MACRO_ECONOMIC AS
SELECT
    TRADE_DATE::DATE AS TRADE_DATE,
    USD_JPY::FLOAT AS USD_JPY,
    NIKKEI_CLOSE::FLOAT AS NIKKEI_CLOSE,
    LOADED_AT
FROM RAW.MACRO_ECONOMIC
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY TRADE_DATE
    ORDER BY LOADED_AT DESC
) = 1;
